### ISSUE TITLE
Oversight in examples, default and/or insert.

### ISSUE THREAD

**Issue by cheako** [hwchen/keyring-rs#103]
It's not clear, or rather ugly, how to perform on-boarding...  That is the first time the application is run using a default value appears clunky.  I guess there are three use cases:

1. Ask the user for secret, the most difficult option.  Perhaps this is the only supported method currently.
2. Substitute a default value, use `or_else` and `if matches!(...` seems clunky.
3. Insert a default value, same trick as with 2 but now you call into the handle.

Catching the `NoEntry` Error is natural enough to have specific helpers for that case.  Variants of `get_password` that take a function argument.  There is also the view that this is not an error, a `get_password` that returns a `Result<Option<String>...` would be another solution.

**Comment by brotskydotcom** [comment]
Thanks for your thoughts, @cheako.  Here is the reasoning for why this crate works the way it does.

None of the secure stores supported by this crate have any notion of a "default value" for a credential: credentials have to be created with explicit values.  In addition, because keyring entries exist independent of the underlying platform credential they are mapped to, the `NoEntry` error value means that the underlying platform credential does not yet exist, and it wouldn't be accurate to return any value in that case (because there is none in the underlying platform).

Clients who have semantics related to "default values" for secure credentials are free to implement that semantics around this crate's interface, and (as you note) this crate provides everything needed to create such an implementation.  Since it would be very client-specific, it's not appropriate to have it in this crate directly.

**Comment by cheako** [comment]
I'm confused, the `NoEntry` error is clearly a default value...  it doesn't matter if ppl classify it as an error it's still the default, an obvious classification problem.

`Option::None` is a sensible value and is part of the rust ecosystem, it indicates the operation was successful but is default.  Arguably, this is what's actually happening when `NoEntry` is returned.

Are you arguing for the existence of a client that does not have a default value, I'd love an explanation.  IMHO every client is run once for the first time and this is unavoidable as far as I'm aware.

Sure, but is there a reason there are no examples of this?  This is the first action devs will take with regard to this crate, so an example would be useful.  It would be proper, not an obstacle, for the example to make a UI call.

**Comment by brotskydotcom** [comment]
@cheako You seem to be focussed on the `get_password` call, which returns a password value if there is a secure credential that matches the entry.  But `NoEntry` is returned from all the calls that access the secure store, even those that don't return values.  That's why it's an error status not a default value.

As for generic secure clients returning a default value from their `get_password` call, I have never seen a client that has one, and certainly none of the platform stores do.

I hope this clarifies the logic of this crate for you.  Of course, as with all program, other approaches could have been taken.  But it's still my belief that the approach taken in this one is consistent and provides useful functionality.

**Comment by landhb** [comment]
@cheako This is something that is typically client specific behavior. (i.e. the decision to prompt the user or insert a default value or load state from disk etc).

You can also create your own wrappers to return what you'd like and handle them according to your applications needs. For example:

```rust
/// Helper to obtain the password, returning None when not
/// yet set.
pub fn get_optional() -> Result<Option<String>, Box<dyn Error>> {
    // Define keyring entry
    let service = env!("CARGO_BIN_NAME");
    let username = whoami::username();
    let entry = Entry::new(service, &username)?;

    // Handle failure
    match entry.get_password() {
        Ok(s) => Ok(Some(s)),
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(e) => Err(e)
    }
}
```

Or

```rust
fn none_or_error(err: keyring::Error) -> Result<Option<String>>, Box<dyn Error>> {
    match err {
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(e) => Err(e)
    }
}


// Usage
let value: Option<String> = entry.get_password().or_else(none_or_error)?;
```
