### ISSUE TITLE
Question: Linux Kernel Keyring lost the saved password after reboot

### ISSUE THREAD

**Issue by Berrysoft** [hwchen/keyring-rs#137]
I'm using this crate in headless mode with kernel keyring. However, my cosumer and myself have found that the saved password will be lost after reboot the system. I haven't found any information or documentation about that. Is it by design? Could I do someting to preserve the password?

**Comment by brotskydotcom** [comment]
cc'ing @landhb since he is more familiar with the kernel keyring.

My understanding (and what's documented in the keyring keystore itself) is that credentials are placed in the user's persistent keyring, which has a default persistence of 3 days.  This lifetime can be adjusted by administrators.  They keystore docs point you at the appropriate man pages for the underlying behaviors.

**Comment by landhb** [comment]
@Berrysoft @brotskydotcom That's correct, the kernel keystore is completely in-memory and will clear on a reboot. 

The "persistent" keyring is persistent across sessions/logins but will still be wiped on a reboot.

Similar to how you need to unlock the Gnome Keyring with a password when you log-in, you'll need to re-prompt your users for a password after a reboot. 

I noticed you're using a systems service, there is a `systemd-ask-password` utility that can be used to prompt the user when your service starts. [manpage](https://www.freedesktop.org/software/systemd/man/systemd-ask-password.html).

**Comment by Berrysoft** [comment]
Thanks @landhb ! I think I need some other ways to save the password then:)

**Comment by brotskydotcom** [comment]
I am reopening this as a doc bug because it's the second time it's come up; I had totally forgotten about it, and it's not documented in the keystore docs.  So I need to fix that.  Thanks for the discussion.

@Berrysoft There is a headless credential keeper for Unix systems called [pass](https://www.passwordstore.org) that you might want to check out.  Here is a [good article](https://www.techrepublic.com/article/how-to-safely-store-passwords-linux-server/) that explains how to run it headless and securely; here is [another article](https://www.redhat.com/sysadmin/management-password-store) that also talks about how to use it with GUI apps such as a browser.  I would certainly welcome the contribution of a `pass`-based keystore for this module.

**Comment by landhb** [comment]
To clarify. This issue is a limitation for all secure storage.

| Backend | Memory Eviction | User Interaction |
| -------------            | -------------         | -------------  | 
| Gnome Keyring                   | On Logout                | User must re-enter their account password to unlock the keyring after logging in again.   Unlocking the keyring with a master/account password allows Gnome to retrieve the encrypted credentials from disk.     |
| Kernel Keyring                  | On Reboot                | User must re-enter the credential or the application must prompt the user for a master password (to decrypt the contents from disk) or obtain the credential from a secure storage medium such as a Yubikey/TPM.         |
| Pass                   | Typically every run            | User must re-enter the master password to decrypt the contents from disk.       |

In general, to have your secrets accessible across reboots, something needs to be able to decrypt/access it securely from the filesystem.

That `passrs` crate is also highly insecure and [stores the keys on disk in plaintext just in reverse order](https://gitlab.com/zevaryx/passrs/-/blob/main/src/keys.rs#L11-L43). So I wouldn't recommend using that crate. I also think password managers in general operate at a higher level of abstraction than this crate. A `pass` implementation could use this crate to store the master password between invocations of the CLI tool for instance.

**Comment by Berrysoft** [comment]
Well, I think I need a beckend that is headless and unlocks on login. Gnome keyring unlocks on login, but it's not headless, and not all users install it. I choose to save the password directly on disk. It is a bit unsafe, but it is convenient.

**Comment by brotskydotcom** [comment]
@landhb Do the persistent credentials in the kernel keyring persist on disk between reboots or not?  In the case of secret-service and pass, the credentials are all persisted on disk and there is a single master password that must be provided to decrypt them.  My impression from your comments above is that the kernel keyring doesn't do any on-disk persistence, so if one has stored multiple credentials in it they are all lost on reboot.  That's quite a different discipline than the others.  That's what I think - if true - needs to be mentioned in the docs.

@Berrysoft The master password for `pass` is the password for the master GPG key used with the store.  Most `pass` users arrange for this to be prompted for at headless login.

**Comment by landhb** [comment]
@brotskydotcom It does not persist on reboot. I agree that it should be mentioned in the docs.

**Comment by brotskydotcom** [comment]
Thanks much to @landhb for the documentation fix (PR #138)!
