### ISSUE TITLE
Editing password from Windows Credentials manage results in spaced password

### ISSUE THREAD

**Issue by dten** [hwchen/keyring-rs#14]
I edited a password I had set to `bananas` but when I get it using `keyring` it showed as `b a n a n a s `
guess that's not meant to happen

**Comment by hwchen** [comment]
Whoops, thanks, I'll look into it

**Comment by hwchen** [comment]
Sorry for delay, I've reproduced the error and will fix asap.

**Comment by dten** [comment]
Cool thanks

**Comment by hwchen** [comment]
Looks like the issue was that I wasn't converting the password to utf16 before passing it to the windows vault. I'd originally done this because the secret blob format is determined by the application, and hadn't expected a use case where the blob would be edited by a third party application.

Thanks for bringing this to my attention, I should have a release tomorrow for you to try.

**Comment by hwchen** [comment]
Resolved by 2078b4776b10ac35d43b13debc5b4f4638d44235

New release 0.6.0 is out on [crates.io](https://crates.io/crates/keyring)

**Comment by dten** [comment]
Thanks
