### ISSUE TITLE
How to remove sensitive data?

### ISSUE THREAD

**Issue by Jarrodsz** [hwchen/keyring-rs#143]
What if implemented this peoject into an app. For example tauri.

Since there is no installer/uninstaller on osx for example how to remove user data from the store after removal of an app?🙏

**Comment by brotskydotcom** [comment]
Each platform credential service provides its own platform-specific UI that allow users to remove credentials from their store (other than the linux keyring, which removes all credentials at reboot).  If you design your application so that it uses a consistent (and distinct) naming convention for credentials it creates (in your case of an app called `tauri`, for example, you might start each service name with the string `tauri-`), then it's easy for users to search for credentials that have that naming convention, and remove them manually.

Hope this helps.
