### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by soywod** [hwchen/keyring-rs#145]
Only `secret_service` truly supports async, but I still think it could be nice to propose both sync and async version of `keyring`. If you are interested in, I can propose sth so we can discuss on.

**Comment by brotskydotcom** [comment]
Thanks for this nice offer, but I must decline.  Personally, I feel that supporting async interfaces over synchronous OS services (which means every keystore but secret service) is a bad idea, especially with the Rust async world in as much flux as it is so that every async module has to make choices about which async infrastructure to support.  I would much rather put effort into supporting the synchronous libdbus interface to secret-service.

**Comment by soywod** [comment]
Thank you for your reply, I totally understand!
