### ISSUE TITLE
Allow using biometric auth (e.g. Touch ID) to get passwords

### ISSUE THREAD

**Issue by gibfahn** [hwchen/keyring-rs#149]
it would be great to be able to allow enabling user presence (e.g. Face ID on an iPhone, Touch ID on a Mac) when storing a password in the keychain. 

macOS docs: [Accessing keychain items with Face ID or Touch ID](https://developer.apple.com/documentation/localauthentication/accessing_keychain_items_with_face_id_or_touch_id?language=objc) say to create the keychain item with [SecAccessControlCreateFlags](https://developer.apple.com/documentation/security/secaccesscontrolcreateflags) to use [kSecAccessControlUserPresence](https://developer.apple.com/documentation/security/secaccesscontrolcreateflags/ksecaccesscontroluserpresence?language=objc) (or similar constraints)

**Comment by brotskydotcom** [comment]
What an interesting idea! To be sure I understand where you're going, is the idea here to increase security, so that an app which wrote a keychain item would not be able to later retrieve it without the user being present? Typically the user's presence is required to unlock the device, rather than again later when the item is being retrieved.

This kind of enhancement would have to be based on an enhancement in the underlying `security-framework` crate which this crate relies on for macOS and iOS. Currently that crate doesn't allow callers to pass in additional flags.

The other concern I would have about this enhancement is that it's very macOS/iOS-specific (at least to my knowledge).  While other platforms support user presence for unlocking the device, they don't support it on an item-by-item basis.  So while I can imagine the macOS and iOS keystore implementations in this crate being enhanced to support this feature, I think clients would probably have to use keystore-specific APIs to set these options rather than the generic keyring interface itself being enhanced to allow setting them.

Do you have a usage context in mind?  I find those very useful when considering enhancements.

**Comment by brotskydotcom** [comment]
Thanks for the use case; that clarifies things.

The dialog you mention is actually Mac-only and appears when the "scope" of an existing item created by one app doesn't allow access by an app with a different developer signature. There's no way to use biometrics to do that unlock, and the security attributes you're talking about don't affect it. That's actually part of Apple's "weaker Mac-only" sandboxing strategy, which is why it isn't on iOS where all apps are sandboxed (and why you always get it when running an unsigned app). It's never shown to the app that authored the item (unless its build has changed and it's not signed).

The security attributes you are talking about are meant to enhance security on items so that not even the author app of the item can get access to the item unless the user is present. This is a level of security above the standard security of requiring the keychain itself to be unlocked (which can always be done with presence).

To answer your other question, yes: this kind of security is very much macOS/iOS-only; it's part of Apple's walled-garden strategy and far beyond what's offered in other OSes whose platforms are intentionally more open.

**Comment by gibfahn** [comment]
> it's part of Apple's walled-garden strategy and far beyond what's offered in other OSes whose platforms are intentionally more open.

Fair enough, although having an opt-in way to say "this data really shouldn't be read without someone actually confirming" seems rather useful to me even as an end-user :grin:,

**Comment by brotskydotcom** [comment]
OK, thanks for getting back on this.  I think it's potentially a useful enhancement, definitely, but not something I'm planning to add (for the reasons outlined above about cross-platform applicability).

**Comment by brotskydotcom** [comment]
Complete control over protected data access has been added to the [apple-native-keyring-store](https://crates.io/crates/apple-native-keyring-store), which relies on [keyring-core](https://crates.io/crates/keyring-core) and is part of the new [Keyring Ecosystem](https://github.com/open-source-cooperative/keyring-rs/wiki/Keyring). That's why this issue is closed.

If you are getting multiple prompts for access to a password using the current keyring, which uses the legacy keychain, then almost for sure it's due to differing builds trying to access the same credential. See #272 for details.
