### ISSUE TITLE
Consider switching to windows crate

### ISSUE THREAD

**Issue by thewh1teagle** [hwchen/keyring-rs#155]
I found that you use [winapi-rs](https://github.com/retep998/winapi-rs) crate for windows related functions which is not updated (2 years already).
Microsoft released official [windows crate](https://github.com/microsoft/windows-rs) for rust for `winapi`.

I used it in [my project](https://github.com/thewh1teagle/rookie/blob/main/rookie-rs/src/common/winapi.rs) for similar things (`dpapi`) in this project:

**Comment by brotskydotcom** [comment]
Thanks for this suggestion.

While I agree the Microsoft windows crate looks promising, it hasn't reached a level of stability that makes me want to do the porting work.  The fact that the winapi-rs crate has not been updated in 2 years is, I believe, simply an artifact of its robustness and the stability of the windows APIs it wraps.

At this point, I think I will hold off until one of the following happens:

- Microsoft releases v1.0 of the windows crate (or otherwise warrants its stability).
- Someone reports a bug in this crate that stems from use of winapi-rs and is fixed in the Microsoft windows crate.
- Someone reports an incompatibility between winapi-rs and other crates that doesn't repro with the Microsoft windows crate.

I am going to leave this bug open pending one of these events.  If you are highly motivated to see this crate use the Microsoft windows crate, feel free to submit a PR with the port, and I'll take a look.
