### ISSUE TITLE
Couldn't access platform secure storage

### ISSUE THREAD

**Issue by darwis059** [hwchen/keyring-rs#167]
i got this error on debian. is there any app to install before this keyring-cli can be use?
`Couldn't set password for '[daily]debian@keyring-cli': Couldn't access platform secure storage: SS error: prompt dismissed`

**Comment by brotskydotcom** [comment]
The error message is indicating that the secret service was not able to prompt you to unlock your secure store.  This sometimes happens when you are using a headless box (or if you are using ssh to access a machine and cannot see its desktop interface).

There is nothing else you need to install in order to use the CLI.  But you have to unlock your secure store before using it, because when the CLI has no way to prompt you from the command line - it relies on the Secret Service to prompt you using your machine's desktop GUI.
