### ISSUE TITLE
[Windows] Credentials are persisted and read with a wrong service key

### ISSUE THREAD

**Issue by dannyyy** [hwchen/keyring-rs#177]
# Overview
Just under Windows, the credentials are read and persisted from a wrong / inconsistent service key. Linux and MacOS behave as expected and differently than Windows.

## Issue
Using `let entry = Entry::new(KEYRING_SERVICE_ID, KEYRING_USER)?;` results in the following behavior:
```
| OS      | Service Name                    | Username     |
------------------------------------------------------------
| MacOS   | KEYRING_SERVICE_ID              | KEYRING_USER |
| Linux   | KEYRING_SERVICE_ID              | KEYRING_USER |
| Windows | KEYRING_USER.KEYRING_SERVICE_ID | KEYRING_USER | <-- ERROR
```
![image](https://github.com/hwchen/keyring-rs/assets/3018863/6896f238-f2e0-4db9-b608-208dbb92c2db)

## Expected
Windows should behave the same way as in MacOS and Linux.
Having the same format is important to maintain compatibility with other credential store libraries in different languages and tools.

```
| OS      | Service Name       | Username     |
-----------------------------------------------
| MacOS   | KEYRING_SERVICE_ID | KEYRING_USER |
| Linux   | KEYRING_SERVICE_ID | KEYRING_USER |
| Windows | KEYRING_SERVICE_ID | KEYRING_USER | 
```

**Comment by dannyyy** [comment]
After digging into the source code of `Windows.rs` I found out how the service name works and how to override it.

If others have the same issue, use `let entry = Entry::new:with_target(KEYRING_SERVICE_ID, KEYRING_SERVICE_ID, KEYRING_USER)?;` to override the service name.

But be careful, this will most probably break Linux and MacOS! The service name is not a valid target name for Unix based systems, as with this argument you chose with kind of store to use. 

Currently, I'm handling that with `#[cfg(target_family = "unix")]` and `#[cfg(target_family = "windows")]`. But I would appreciate having a more concise interface for `keyring-rs`. That's why I will left open this issue.

**Comment by brotskydotcom** [comment]
Hi @dannyyy. Yes, the behavior on Windows is different.  This is as designed, and explained at length in the crate's documentation (look at the Windows credential store). Keyring works this way because both the `service` and `user` fields are used for identifying credentials on the native Mac and Linux credential stores, but only the `service` field is used on the native Windows credential store.  So if Keyring used the same conventions on Windows that it uses on Mac and Linux, two credentials for the same service and different users would overwrite each other.

Keep in mind that the actual values used in the native credential stores don't matter to keyring clients.  Only if you are trying to interoperate with other clients (such as the python keyring module) do the native store value matter. The convention used by this crate is actually based on the convention used by the python keyring module when there are multiple user credentials for the same service.
