### ISSUE TITLE
Changelog not updated with 3.0

### ISSUE THREAD

**Issue by VorpalBlade** [hwchen/keyring-rs#189]
CHANGELOG.md appears to not contain anything after version 2.0.1?

**Comment by VorpalBlade** [comment]
I would especially appreciate if the changelog contained info such as "what happened to the `platform-freebsd` feature" (which doesn't seem to have a direct replacement).

**Comment by brotskydotcom** [comment]
So sorry for missing the changelog update in this release! I'll get on that right away.

All of the `platform-*` features have gone away in this release.  Instead, you control which specific credential stores you want to include by specifying their specific features, and your build will contain all the specified ones that work on your build platform.  So, for example, if you specify the `dbus-secret-service` and `apple-native` features and you build for OS `freebsd`, you will get the `dbus-secret-service` credential store. If you use the same build command on macOS, you will get the Keychain credential store.  I will update the README to explain this.

Thanks for the thanks! Having to tack on an async runtime in order to use this crate has been a pet peeve of mine since v2!
