### ISSUE TITLE
3.0.3 Doesn't return error when having storage access failures

### ISSUE THREAD

**Issue by shard77** [hwchen/keyring-rs#196]
Hello, I just upgraded from 2.3.2 to 3.0.3, and added the required features in my `Cargo.toml` as requested. For some reason, 3.0.3 `Entry::new` doesn't return any error anymore when failing to access the platform secure storage.

As an example:

Running on 2.3.2:
```
Entry {
    inner: Any { .. },
}
Err: Couldn't access platform secure storage: SS error: result not returned from SS API
```

Trying with 3.0.3, using the features `linux-native`, `apple-native` and `windows-native`:
```
Entry {
    inner: Any { .. },
}
Auth token has been stored successfully. // shouldn't be the case, it should throw the same error as 2.3.2 does 
```

Snippet from my code:
```rust
pub fn store_secret(
    entry_service: &str,
    entry_name: &str,
    credential: &str,
) -> keyring::Result<()> {
    let entry = Entry::new(entry_service, entry_name)?;
    entry.set_password(credential)?;
    Ok(())
}
```

I then unwrap the result, which leads to an error on 2.3.2 (when having no keyring back-end or simply a bad configuration).

Note that I have the same keyring configuration between the two runs and I can easily change the crate version to reproduce the error.
I am using `gnome-keyring` under WSL2 (Windows Subsystem For Linux).

**Comment by brotskydotcom** [comment]
Hi, @shard77, thanks much for bringing this to my attention.  The error you are receiving on v2.3.2 indicates that you are using the Secret Service credential store, but the features you are specifying with 3.0.3 (`linux-native`) indicate you are using the Linux keyring credential store. Because the Linux keyring credential store is always available and doesn't need to be unlocked, you will generally not receive an error when setting a (non-empty) password in it.

In order to use the Secret Service credential store with v3.0.3 you will need to remove the `linux-native` feature and add either the `sync-secret-service` or the `async-secret-service` feature. (And, if you decide to use the async support for the secret service, which was the default in v2.3.2, you also will need to specify a crypto feature and an async runtime feature.) Exactly which feature can be used to enable a particular credential store on a particular platform is detailed in the [module documentation](https://docs.rs/keyring/latest/keyring/#credential-store-features).

Please let me know if this solves your problem.

**Comment by shard77** [comment]
> Hi, @shard77, thanks much for bringing this to my attention. The error you are receiving on v2.3.2 indicates that you are using the Secret Service credential store, but the features you are specifying with 3.0.3 (`linux-native`) indicate you are using the Linux keyring credential store. Because the Linux keyring credential store is always available and doesn't need to be unlocked, you will generally not receive an error when setting a (non-empty) password in it.
> 
> In order to use the Secret Service credential store with v3.0.3 you will need to remove the `linux-native` feature and add either the `sync-secret-service` or the `async-secret-service` feature. (And, if you decide to use the async support for the secret service, which was the default in v2.3.2, you also will need to specify a crypto feature and an async runtime feature.) Exactly which feature can be used to enable a particular credential store on a particular platform is detailed in the [module documentation](https://docs.rs/keyring/latest/keyring/#credential-store-features).
> 
> Please let me know if this solves your problem.

Ah I see, that makes sense. Much thanks for the answer!
Just a question because I'm kind of confused, does it mean that the logic for throwing such errors on v2.3.2 has been removed on v3.0.3? The thing is that if I'm going to end up using `sync-secret-service` or `async-secret-service`, I'd need to install additional dependencies, and this is rather inconvenient for me.

**Comment by brotskydotcom** [comment]
Hi @shard77 glad that answer was helpful.  It looks like you edited a second question out of your comment, so probably you figured out the answer, but just in case I'll answer that question anyway:

- the error handling in 3.0.3 is exactly the same as it was in v2.3.2, so once you switch to using the secret service (either sync or async) things will work the same as they did for you in v2.3.2.

Thanks for using keyring and contributing!

**Comment by shard77** [comment]
> Hi @shard77 glad that answer was helpful. It looks like you edited a second question out of your comment, so probably you figured out the answer, but just in case I'll answer that question anyway:
> 
>     * the error handling in 3.0.3 is exactly the same as it was in v2.3.2, so once you switch to using the secret service (either sync or async) things will work the same as they did for you in v2.3.2.
> 
> 
> Thanks for using keyring and contributing!

Yeah I found it out :) - thanks for the confirmation!
