### ISSUE TITLE
Clarify distinction between target, user, and service

### ISSUE THREAD

**Issue by JosiahParry** [hwchen/keyring-rs#206]
Thank you for the wonderful crate! I am trying to wrap my head around how to best utilize this crate for cross-platform development. However it isn't clear to me what the arguments refer to when creating a new `Entry`. 

For example, when using `apple-native` feature with 
```rs
let ent = Entry::new_with_target("target", "my-service", "my-user").unwrap();
```
I get the following runtime error:
```
`Result::unwrap()` on an `Err` value: Invalid("target", "'target' is not User, System, Common, or Dynamic")
```
Which is unexpected because `target` is provided to the target argument and not the `user` argument. 

Would you be able to clarify how these arguments are intended to be used? My understanding was: 

- service refers to the app that I'm building 
- user is the user who would be running the app
- target is the name of the credential i want to create

but it seems that this isn't the case.

**Comment by brotskydotcom** [comment]
Hi there, thanks for asking this question. Let me see if I can clarify things for you.

- The _target_ parameter is completely optional, so if you don't have a specific reason for using it then my recommendation is not to.  Rather than calling `Entry::new_with_target`, I suggest you call `Entry::new`, which takes only the user and service arguments.
- The function of the target parameter is to allow compatibility with 3rd-party credential services that may use different conventions for mapping a _user_ and _service_ values into platform-specific credential values. Because this behavior is platform-specific, use of the _target_ parameter typically has to be conditionalized by platform in your code.
 - You got the error message shown because, on macOS/iOS, the _target_ parameter allows you to specify which of the keychains on the system your credential is in (or should be placed in).  These are called the _System_, _User_, _Dynamic_, and _Common_ keychains—if you open your `Keychain` application you will see the _System_ and _Login_ (aka User) keychains as choices by default—which is why you got that error message specifying that you have to use one of those values for your target parameter.

Please feel free to comment again here if this doesn't clarify things for you.
