### ISSUE TITLE
Question: how does the persistence work? I can't make password persist in example.

### ISSUE THREAD

**Issue by HuakunShen** [hwchen/keyring-rs#231]
For example, I ran the example `keyring-cli` from the repo

```bash
cargo run --example keyring-cli set --password hello
cargo run --example keyring-cli password
```

**Comment by HuakunShen** [comment]
This example works though

```rust
use keyring::{Entry, Result};

fn main() -> Result<()> {
    let entry = Entry::new("my-service", "my-name")?;
    entry.set_password("topS3cr3tP4$$w0rd")?;
    let password = entry.get_password()?;
    println!("My password is '{}'", password);
    // entry.delete_credential()?;
    Ok(())
}
```

**Comment by brotskydotcom** [comment]
Persistence is handled by the credential store module selected when the crate is compiled, and this selection is done via features. The pre-compiled versions of the CLI downloadable from GitHub use the native platform keystrokes, which means they will provide full persistence on Apple and Windows platforms, and persistence for a few days or until reboot (whichever comes first) on Linux platforms. They will provide no persistence at all on other *nix platforms.

If you are compiling keyring yourself, be sure to specify a feature for a persistent keystore on your target platform, otherwise you will get the mock keystore which doesn't have any persistence beyond a single run of an application (credentials vanish when the application exits).  For example, you will want to use the `apple-native` feature on macOS, the `windows-native` feature on Windows, and the `sync-secret-store` on any *nix platform. That will provide full persistence until credentials are deleted explicitly.

I'm going to close this question as answered, but feel free to keep posting if you need more information, and I will reply.
