### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by clintfred** [hwchen/keyring-rs#42]
I may be way out in left field here, but would it every make sense to add support for android and iOS to keyring-rs? It seems like a unified keyring interface could be powerful as Rust continues to make inroads into the mobile space.

**Comment by hwchen** [comment]
I'm not familiar enough with android and iOS to know if it would be valuable? If there's a use case, I'm happy to support it though :)

**Comment by adobeDan** [comment]
@clintfred We are in the middle of revamping our platform support, and I believe we can probably support iOS fairly soon (because the Mac Secure Keychain APIs are roughly the same as on iOS).  I don't know enough about Android to know whether it supports the dbus library for IPC that the Linux secret-service depends on.  So probably I will work on iOS support sometime in the next month or two, after the platform support revamp is complete, and that might provide you a good base for doing the same extension on the Linux/Android side.

**Comment by brotskydotcom** [comment]
OK so I have done a bunch of investigation into the iOS side of this and it's definitely a no-go as things stand today 😢.  MacOS and iOS have subtly different keychain support, and it looks like the Rust-supported platform interfaces are missing support for adding keychain entries on iOS.  I will ask a question of the maintainers about this, but before we add support in this module we are going to need the platform support.

Sorry I'm sorry @clintfred but for now I have to mark this as "won't fix".

**Comment by brotskydotcom** [comment]
I've now contributed iOS support to the rust security-framework, and am extending keyring to support iOS.
