### ISSUE TITLE
Use `zeroize`

### ISSUE THREAD

**Issue by WilliamVenner** [hwchen/keyring-rs#77]
Hi, when I came across this crate, [`zeroize`](https://docs.rs/zeroize/latest/zeroize/) came to mind, would this crate potentially benefit from zeroing out credentials when dropped?

**Comment by brotskydotcom** [comment]
Hi @WilliamVenner, good question. My take is no, for the following reasons:

- the actual persistent storage of the credentials is in the platform credential store, which is encrypted and presumably secure against infiltration to discover dropped credentials.
- all this crate does is transport credentials in memory transiently; the actual in-memory persistent copy of the credential is returned to the caller on every call (and thus the caller could clear it).
- because (like all Rust crates) any transient copies of the credential are returned to the memory allocator as soon as the call returns, it would not be easy for an attacker to locate a transient copy that had been left behind.

Hope this answer is helpful.
