### ISSUE TITLE
Supporting pass as a fallback on linux

### ISSUE THREAD

**Issue by Sytten** [hwchen/keyring-rs#95]
Many headless linux don't have a great way to work with secret-service. This is detailed in the documentation already, though I had to also launch the dbus daemon with `export $(dbus-launch)` which I found [here](https://github.com/zowe/zowe-cli-scs-plugin/blob/master/README.md#linux-headless).
I think a good fallback would be to use pass as this is what docker does too to store credentials (searching for `cannot autolaunch d-bus without x11 $display` yields a bunch of response going in that direction).

**Comment by brotskydotcom** [comment]
@Sytten I assume you are talking about [this pass](https://www.passwordstore.org/).  I like that idea a lot, since I have personally been bitten by how useless secret-service is on headless servers (which, to my way of thinking, have some of the biggest needs for storing passwords).

Since pass is so flexible in how it stores things, we would have to come up with some keyring-specific conventions for what credentials look like.  Plus we'd have to split the "Linux" platform into two variants: LinuxKeyring and LinuxPass.  It would be a lot simpler to use features for that instead of introducing runtime configuration (although I suspect the runtime configuration might be useful for other reasons).  Do you foresee any situations where someone might need `keyring` to bridge between secret-service and pass?  Do you know of any apps that use both?

**Comment by Sytten** [comment]
Yes I am talking about this pass! We have the issue where a lot of our users run their server on headless and secret-service is usually not enabled (nor unlocked).

I would prefer to have the two options at runtime since I will prefer secret-service over pass when it's available. One other thing I need to figure out is how to ask the user to unlock the vault since our service is usually started on boot without user interaction.

**Comment by brotskydotcom** [comment]
So I've been looking at pass more closely and it's not really suited for use from an API.  It's basically a collection of shell scripts, which presents some pretty big problems (from my perspective):

1. The overhead of starting and running not just one but two processes (the shell script and the `gpg` call) on every API access seems insanely high.
2. There is no good mechanism for communicating error states, or even understanding whether it's the shell script or the `gpg` command that's running into problems.
3. There is no way to control the presentation of `gpg` UI during the execution of the calling program.

Until someone comes up with a way of accessing pass data via a more controlled API, I don't quite see how it could be used by this package.  @Sytten, any thoughts?

**Comment by Sytten** [comment]
Hum those are very good points, I will investigate a bit more pass. There is a similar issue with secret service and the unlock function, which keyring currently just ignores and sets as a prerequisite (that is another discussion to be had). Solving that would be a good step in solving point 3

For points 1 and 2, I am wondring if a better approach would be to use a reimplementation like https://crates.io/crates/passrs that is compatible but built on primitives we can control.

**Comment by brotskydotcom** [comment]
@Sytten, thanks for tracking down the [passrs crate](https://crates.io/crates/passrs)!  I think that may actually be a better solution than keyring in the headless server case: see my side comment at the very end of this note.

I think we are getting to a fundamental design question concerning _this_ crate: is it meant to be a wrapper for the "native secure storage" of the underlying platform or is it meant to be a self-contained mechanism that allows storage and retrieval of secrets on all three platforms?

From my perspective (and I think @hwchen would agree), the answer is the former: this crate is meant to be a wrapper for the "native secure storage" of the underlying platform (much as the [python keyring](https://pypi.org/project/keyring/) is).  As such, it relies on that underlying platform store to communicate with the user for authentication/unlock purposes, and expects such UI not to interfere with the UI that may be presented by the process that is running keyring.

Putting this another way: this crate views the underlying platform security mechanism as a faceless service which has its own client running in another process unrelated to the keyring client. In the case of the mac keyring, the windows secure store, and the Linux secret-service/Gnome keyring *on headed machines*, this view of the underlying security mechanism is correct: the secure store provides its own client-side UI for doing lock and unlock of the secure store for an authenticated user.  But in the case of headless Linux servers, this is not (by default) an accurate view; rather, the owner of the headless system must take steps to provide an independent unlock mechanism for the secure store in order for keyring to function properly.

There have been (several) issues raised here that request keyring to attempt unlock of secret-store vaults. In my view, those issues really get at this same underlying question, and they haven't gotten attention because they are asking keyring to do something it wasn't designed to do.  From keyring's perspective, it's the responsibility of the platform secure store, not this crate, to prompt the user as needed for unlock.

Based on this line of thought, I'm inclined to mark this issue as "won't fix".  But I'm happy to let you try to talk me out of that first :).

Side comment: In my opinion, the biggest advantage of the current approach of this crate is that it allows interoperation with other clients of the same secure store.  A lot of effort went into the v1 release to ensure that keyring clients could specify the naming and indexing of credentials; this work was done specifically to make this interoperability reliable.  It seems to me that this interoperability is primarily needed on thick (headed) clients where users run lots of different processes that may share passwords.  In today's world of single-purpose containers and virtual machines, I'm not at all sure that this interoperability is really an issue: how many different processes are trying to interoperate with passwords on the same headless server?  In many ways, I think a create like `passrs` is much more on point for headless server storage that works on multiple platforms than keyring is.

**Comment by Sytten** [comment]
Hum good points. I feel that maybe keyring should not unlock by default but should provide the primitives to abstract away the unlock and let the user of the crate handle how they want to unlock.

As per the integration of pass itself, it could be considered a won't fix yes. I would find it a bit annoying myself since that does mean having to make an exception on linux for cases where keyring cannot work vs just having nicely following the same patterns as the rest of the platforms.

I feel a good compromise could be to create some traits that could be implemented by third party crates to provide access to other storages (hashicorp vault for example). That would make keyring really shine in the ecosystem I think and would reduce your maintenance burden.

But maybe it is out of scope for this crate too. Just let me know!

**Comment by landhb** [comment]
I believe the most correct solution for a keyring on Linux without relying on an environment provided keyring like on KDE/Gnome is the one that has been provided by the kernel since Linux 2.6. Which also has a default keyring tied to UID:

https://man7.org/linux/man-pages/man7/keyrings.7.html

Using pass won't prevent the problem of needing to store secrets securely. Because pass itself needs somewhere to store identities/keys, which is normally done in a keyring/GPG agent after authentication.

Side note; that `passrs` library linked seems to be storing its master keys unencrypted on disk? 

https://gitlab.com/zevaryx/passrs/-/blob/main/src/keys.rs#L16

Which is vastly different than the original `pass` utility. And not secure.

**Comment by brotskydotcom** [comment]
Great discussion, @Sytten and @landhb, thanks!  It is wonderfully helpful for me as a maintainer to get this feedback (and reassuring that some folks at least are using the crate :).

@landhb thanks so much for the pointer to Linux in-built keyrings!  I do not have the kind of in-depth background on Linux that I do on Mac and Windows so this kind of education is invaluable for me.  I agree that these do look like a perfect back-end for keyring to be able to use on that platform!

@Sytten You are not the first to suggest that we handle platforms as traits so as to allow plugging in other back ends (including those for mocking) - see #94.  Between this issue and that one I am becoming more convinced that this is a direction we should be heading.  Especially since it's now clear we don't really want to support just one mechanism or another on Linux.

I guess I will start on a v2 that addresses both these issues (support for native keyrings on Linux, and traits to allow pluggable back-ends).  Probably I'll start an issue for discussion of that rather than try to continue it here.  I'll tag you both once I open that issue.

**Comment by landhb** [comment]
@brotskydotcom I had a look at that other repo and just decided to write a Rust interface for keyutils. Hopefully it's useful enough for `keyring` to use as a backend.

[Repository](https://github.com/landhb/linux-keyutils)
[Docs](https://docs.rs/linux-keyutils/0.1.0/linux_keyutils/)
[Crates.io](https://crates.io/crates/linux-keyutils)

Basic usage:

```rust
use linux_keyutils::{Key, KeyRing, KeyError, KeyRingIdentifier};
use linux_keyutils::{KeyPermissionsBuilder, Permission};

fn main() -> Result<(), KeyError> {
    // Obtain the default session keyring for the current process
    // See [KeyRingIdentifier] and `man 7 keyrings` for more information on default
    // keyrings for processes.
    let ring = KeyRing::from_special_id(KeyRingIdentifier::Session, false)?;

    // Insert a new key
    let key = ring.add_key("my-new-key", b"secret")?;

    // Utiltiies to create proper permissions
    let perms = KeyPermissionsBuilder::builder()
        .posessor(Permission::ALL)
        .user(Permission::ALL)
        .group(Permission::VIEW | Permission::READ)
        .build();

    // Perform manipulations on the key such as setting permissions
    key.set_perm(perms)?;

    // Or setting a timeout for how long the key should exist
    key.set_timeout(300)?;

    // Or invalidating (removing) the key
    key.invalidate()?;
    Ok(())
}
```

**Comment by brotskydotcom** [comment]
@landhb Your timing is perfect, thanks!  After doing a bunch of reading of keyrings-related man pages, and then looking at the existing keyutils crate, I had decided to build the traits and plug-ability of implementations first and then look at whether I could do a keyring-based implementation.  Your crate looks way better for that than the existing one, so thanks!

I have a question for you, as a keyring newbie on Linux who has a lot of experience with keyrings on other platforms: It looks to me like keyring entries are pretty much always ephemeral, not permanent like those on Mac and Win.  The only semi-permanent one (that survives user logout, for example), is the user-specific "persistent" keyring intended for cron jobs to use, but even that has quite a short lifetime by default.  Am I reading that right in the docs?

If I have that right, then I'm thinking that secret-service will need to remain the "default" implementation of keyring on Linux, so that the key lifetimes match up with those expected on other platforms.  I would include the keyring implementation for headless users who don't need permanence, but they would have to choose it explicitly.

**Comment by landhb** [comment]
@brotskydotcom No problem!

I believe your interpretation of the man pages is correct. The kernel keyring seems to be entirely in memory and ephemeral. Just with varying levels of longevity. So it would be appropriate to have the backend opt-in for users creating a headless Linux service or running on systems that don't use Gnome (one of my use-cases is my Arch i3wm laptop).

The "persistent" keyrings will persist between logins but not over reboots. And will expire if not accessed within the system's setting for:

```
/proc/sys/kernel/keys/persistent_keyring_expiry
```

Which I believe is set to 3 days by default. But the library user setting up a headless service can extend the default and have their service re-init the keyring after a reboot via their init system that they're using to re-start the service itself. It's also typically more rare to require a reboot for Linux servers.

I've added [KeyRing::get_persistent](https://docs.rs/linux-keyutils/latest/linux_keyutils/struct.KeyRing.html#method.get_persistent) to support this use case. So a sane selection for this `keyring` crate backend would probably be:

```rust
let ring = KeyRing::get_persistent(KeyRingIdentifier::Session)?;
```

or

```rust
let ring = KeyRing::get_persistent(KeyRingIdentifier::User)?;
```

I imagine a library user creating a headless systemd service would have a service file that prompts the user for a password on boot via `systemd-ask-password` to re-initialize the service, and then will just periodically call `Entry::new` to keep it in-memory. And the admin setting up the service can also extend the timeout via:

```bash
echo "2592000" | sudo tee -a /proc/sys/kernel/keys/persistent_keyring_expiry
```

To extend it to something like 30 days. For interactive programs like the one I'm making I've just been re-prompting for auth once the keyring entry is no-longer valid and re-initialize it from an encrypted file on disk:

```rust
Self::from_keyring(&entry, cfg).or_else(|_| Self::from_disk(&entry, cfg))
```

**Comment by landhb** [comment]
Actually they may not even need to call `Entry::new` periodically if the keyring is linked to the session. But I'll have to test that. 

It may actually be preferred to just use the User/Session keyrings themselves without a timeout if the systemd service they are making is tied to its own UID.

**Comment by brotskydotcom** [comment]
Hi all, I've gotten to a proposed alpha release for the enhancements we've been discussing.  Please provide any design comments on #97 and any code feedback on #98.  I'll leave this issue open for @landhb to report progress on his new kernel-based provider.

**Comment by landhb** [comment]
I think an intial impl of the new traits would probably look something like:

```rust
//! Example implementation of the keyring crate's trait interface
//! using linux-keyutils
use keyring::credential::{CredentialApi, CredentialBuilderApi};
use keyring::{
    Credential,
    Error::{BadEncoding, PlatformFailure},
    Result,
};
use linux_keyutils::{KeyRing, KeyRingIdentifier};
use std::any::Any;

/// Since the CredentialBuilderApi::build method does not provide
/// an initial secret, this wraps a linux_keyutils::KeyRing instead
/// of a linux_keyutils::Key. Since it is impossible to have a
/// zero-length key.
///
/// The added benefit is any call to get_password before set_password
/// will result in a proper error as the key does not exist until 
/// set_password is called.
#[derive(Debug, Clone)]
struct LinuxNativeCredential {
    /// Host keyring
    inner: KeyRing,
    /// Description of the key entry
    description: String,
}

/// Simple abstraction around building access to a persistent
/// keyring.
#[derive(Debug, Copy, Clone)]
struct LinuxNativeCredentialBuilder;

/// A keyutils credential builder based off the persistent user-session
/// keyring.
impl CredentialBuilderApi for LinuxNativeCredentialBuilder {

    /// Attempt to access the persistent user-session keyring. The
    /// keyring::Entry will be invalid until Entry::set_password is set.
    fn build(&self, _target: Option<&str>, service: &str, user: &str) -> Result<Box<Credential>> {
        // Obtain the user-session keyring
        let ring = KeyRing::get_persistent(KeyRingIdentifier::UserSession)
            .map_err(|e| PlatformFailure(e.into()))?;

        // Construct the credential
        Ok(Box::new(LinuxNativeCredential {
            inner: ring,
            description: format!("{}-{}", service, user),
        }))
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}

impl CredentialApi for LinuxNativeCredential {
    /// Set a password in the underlying store
    ///
    /// This will overwrite the entry if it already exists since
    /// it's using `add_key` under the hood.
    fn set_password(&self, password: &str) -> Result<()> {
        self.inner
            .add_key(&self.description, password)
            .map_err(|e| PlatformFailure(e.into()))?;
        Ok(())
    }

    /// Retrieve a password from the underlying store
    ///
    /// This requires a call to `Key::read` with checked conversions
    /// to a utf8 Rust string.
    fn get_password(&self) -> Result<String> {
        // Verify that the key exists and is valid
        let key = self
            .inner
            .search(&self.description)
            .map_err(|e| PlatformFailure(e.into()))?;

        // Allocate enough room for a full UserKey
        let mut buffer = vec![0u8; 65535];

        // Read in the full key
        let len = key
            .read(&mut buffer)
            .map_err(|e| PlatformFailure(e.into()))?;

        // Update vector with the number of bytes read
        unsafe {
            buffer.set_len(len);
        }

        // Attempt utf-8 conversion
        let s = std::str::from_utf8(&buffer[..len]).or(Err(BadEncoding(buffer.clone())))?;

        // Ensure the payload is valid utf8
        Ok(s.to_string())
    }

    /// Delete a password from the underlying store.
    ///
    /// Under the hood this uses `Key::invalidate` to immediately
    /// invalidatee the key and prevent any further successful
    /// searches.
    fn delete_password(&self) -> Result<()> {
        // Verify that the key exists and is valid
        let key = self
            .inner
            .search(&self.description)
            .map_err(|e| PlatformFailure(e.into()))?;

        // Invalidate the key immediately
        key.invalidate().map_err(|e| PlatformFailure(e.into()))?;
        Ok(())
    }

    /// Cast the credential object to Any.  This allows clients
    /// to downcast the credential to its concrete type so they
    /// can do platform-specific things with it (e.g, unlock it)
    fn as_any(&self) -> &dyn Any {
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use keyring::Entry;

    #[test]
    fn test_new() {
        // set the proper backend
        keyring::set_default_credential_builder(Box::new(LinuxNativeCredentialBuilder));

        // start an antry
        let _entry = Entry::new("myservice", "keyid-0").unwrap();
    }

    #[test]
    fn test_get_set_password() {
        // set the proper backend
        keyring::set_default_credential_builder(Box::new(LinuxNativeCredentialBuilder));

        // start an entry
        let entry = Entry::new("myservice", "keyid-1").unwrap();

        // attempt to get the password before it is created
        assert!(entry.get_password().is_err());

        // set the password
        entry.set_password("secretpassword").unwrap();

        // read back the password and confirm they match
        let password = entry.get_password().unwrap();
        assert_eq!(password, "secretpassword");

        // delete it
        entry.delete_password().unwrap();
    }

    #[test]
    fn test_delete() {
        // set the proper backend
        keyring::set_default_credential_builder(Box::new(LinuxNativeCredentialBuilder));

        // start an entry
        let entry = Entry::new(&LinuxNativeCredentialBuilder, "myservice", "keyid-2").unwrap();

        // shouldn't exist yet
        assert!(entry.get_password().is_err());

        // set the password
        entry.set_password("secretpassword").unwrap();

        // it exists now
        assert!(entry.get_password().is_ok());

        // delete it
        entry.delete_password().unwrap();

        // doesn't exist anymore
        assert!(entry.get_password().is_err());
    }
}
```

**Comment by landhb** [comment]
I'm not sure if you're open to having the implementation available to users of the library directly. But if so, it could be added as a cargo-feature:

```
[features]
default = ["secret-service"]
secret-service = []
linux-keyutils = []

[target.'cfg(target_os = "linux")'.dependencies]
secret-service = "2.0"
linux-keyutils = "0.2"
```

And then in `lib.rs`:

```rust
// Default platform-specific implementations
#[cfg_attr(all(target_os = "linux", feature="secret-service"), path = "linux.rs")]
#[cfg_attr(all(target_os = "linux", feature="linux-keyutils"), path = "linux-keyutils.rs")]
#[cfg_attr(target_os = "windows", path = "windows.rs")]
#[cfg_attr(target_os = "macos", path = "macos.rs")]
#[cfg_attr(target_os = "ios", path = "ios.rs")]
pub mod default;
```

And then users that need the headless implementation would put this in their Cargo.toml:

```
keyring = {version = "2.0", default-features = false, features = ["linux-keyutils"]}

**Comment by brotskydotcom** [comment]
Hi @landhb, yes, I was planning to include additional providers in much the way you suggest in your comment above.  Ironically, if it weren't for backward compatibility issues, I would actually make the linux-keyutils implementation the default one, because it's the only one that works well both on headless and headed systems.

Thanks for your implementation outline, by the way.  Now that I've finished updating Mac, I will pick it up and try to get it working in an alpha.2.

**Comment by landhb** [comment]
Sweet sounds good! Thanks for all the recent API updates 💪

**Comment by landhb** [comment]
@brotskydotcom I just upgrade from `1.2.0` to  `"2.0.0-alpha.2"` with the keyutils feature in my other project and it was essentially a drop in replacement! 

New trait interface is an easy transition just added `?` to my `Entry::new` call haha

**Comment by brotskydotcom** [comment]
@landhb Terrific!  Thanks for the feedback.  I'm about to push an alpha.3 that fixes an issue with checking for a key right after invalidation: sometimes you would get a PlatformFailure error instead of a NoEntry error.  At that point I will close this issue - thanks so much for all your contributions (which will be acknowledged in the readme!)
